version: "3"
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    networks:
      - anytore-internal-net
    restart: always
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes:
      - dynamodb-local-data:/home/dynamodblocal/data

  user-db:
    image: mysql:8.0
    networks:
      - anytore-internal-net
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: anytore
      MYSQL_USER: develop
      MYSQL_PASSWORD: example
    volumes:
      - user-db-data:/var/lib/mysql

  anytore-backend:
    image: anytore/backend:latest
    networks:
      - anytore-internal-net
      - anytore-external-net
    restart: always
    ports:
      - "8082:80"
    environment:
      - GIN_MODE=debug
      - LOG_LEVEL=debug
      - DB_USER=develop
      - DB_PASSWORD=example
      - DB_HOST=user-db
      - DYNAMODB=local
      - LOCAL_DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - TOKEN_SECRET=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      - CORS_ORIGIN=*
      - ADMIN_NAME=localadmin
    depends_on:
      - dynamodb-local
      - user-db

networks:
  anytore-internal-net:
    internal: true
    driver: bridge
  anytore-external-net:
    driver: bridge

volumes:
  dynamodb-local-data: {}
  user-db-data: {}
