# anytore config
## env: LOG_LEVEL, value: debug or info
LOG_LEVEL: debug

# Gin config
## env: GIN_MODE, value: debug or release
GIN_MODE: debug

# AWS config
## env: AWS_REGION, value: ap-northeast-1, us-east-1, ...
AWS_REGION: ap-northeast-1
