name: Create App Runner service
run-name: Execute terraform and create App Runner service

on: [ workflow_dispatch ]

env:
  AWS_REGION: ap-northeast-1

permissions:
  id-token: write

jobs:
  CreateService:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.GH_ACTION_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Init terraform
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TFSTATE_BUCKET_NAME }}" \
            -backend-config="key=${{ secrets.TFSTATE_NAME }}"
        working-directory: ./platform/aws

      - name: Apply terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          TF_VAR_repository_name: ${{ secrets.REPOSITORY }}
          TF_VAR_image_tag: ${{ secrets.RELEASE_IMAGE_TAG }}
          TF_VAR_service_name: ${{ secrets.SERVICE_NAME }}
        working-directory: ./platform/aws
